=== heavenlxj/emgui/src/schema/initital.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ship_name" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="call_sign" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="imo_number" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="port_registry" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="company_name" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="class_society" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="email" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="telphone" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="fax" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="ship_type" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="international_gross_tonnage" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="international_net_tonnage" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="loa" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lbp" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="breadth_moulded" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="depth_moulded" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="ecdis_maker" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="model" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="master_name" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="master_crew_id" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="maintain_paper_chart" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="ME_Particular" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ME_Brand" type="xs:string"/>
	<xs:element name="ME_Model" type="xs:string"/>
	<xs:element name="ME_Particular">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ME_Brand" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="ME_Model" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="ME_Table" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ME_Table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cell" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="breadth_moulded" type="xs:string"/>
	<xs:element name="call_sign" type="xs:string"/>
	<xs:element name="cell">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="row" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="d_row"/>
								<xs:enumeration value="slow"/>
								<xs:enumeration value="half"/>
								<xs:enumeration value="full"/>
								<xs:enumeration value="nav_full"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="column" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="rpm"/>
								<xs:enumeration value="ballast_speed"/>
								<xs:enumeration value="ballast_slip"/>
								<xs:enumeration value="load_speed"/>
								<xs:enumeration value="load_slip"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="class_society" type="xs:string"/>
	<xs:element name="company_name" type="xs:string"/>
	<xs:element name="depth_moulded" type="xs:string"/>
	<xs:element name="ecdis_maker" type="xs:string"/>
	<xs:element name="email" type="xs:string"/>
	<xs:element name="fax" type="xs:string"/>
	<xs:element name="imo_number" type="xs:string"/>
	<xs:element name="initial_report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="international_gross_tonnage" type="xs:string"/>
	<xs:element name="international_net_tonnage" type="xs:string"/>
	<xs:element name="lbp" type="xs:string"/>
	<xs:element name="loa" type="xs:string"/>
	<xs:element name="maintain_paper_chart" type="xs:short"/>
	<xs:element name="master_crew_id" type="xs:string"/>
	<xs:element name="master_name" type="xs:string"/>
	<xs:element name="model" type="xs:string"/>
	<xs:element name="port_registry" type="xs:string"/>
	<xs:element name="ship_name" type="xs:string"/>
	<xs:element name="ship_type" type="xs:string"/>
	<xs:element name="telphone" type="xs:string"/>
</xs:schema>

=== heavenlxj/emgui/src/schema/initial_report.xml
<?xml version="1.0" encoding="UTF-8"?>
<initial_report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="initital.xsd">
	<Property>
		<ship_name/>
		<call_sign/>
		<imo_number/>
		<port_registry/>
		<company_name/>
		<class_society/>
		<email/>
		<telephone/>
		<fax/>
		<ship_type/>
		<international_gross_tonnage/>
		<international_net_tonnage/>
		<loa/>
		<lbp/>
		<breadth_moulded/>
		<depth_moulded/>
		<ecdis_maker/>
		<model/>
		<master_name/>
		<master_crew_id/>
		<maintain_paper_chart>1</maintain_paper_chart>
		<ME_Particular>
			<ME_Maker/>
			<ME_Model/>
			<ME_Table/>
		</ME_Particular>
	</Property>
</initial_report>
