=== heavenlxj/emgui/src/schema/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by 123 (456) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ship_name"/>
				<xs:element ref="call_sign"/>
				<xs:element ref="voyage_number"/>
				<xs:element ref="captain_name"/>
				<xs:element ref="date"/>
				<xs:element ref="route_id_number"/>
				<xs:element ref="routes"/>
				<xs:element ref="reason_objection"/>
				<xs:element ref="remark"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="call_sign" type="xs:string"/>
	<xs:element name="captain_name" type="xs:string"/>
	<xs:element name="date" type="xs:date"/>
	<xs:element name="lat" type="xs:int"/>
	<xs:element name="long" type="xs:int"/>
	<xs:element name="objection_report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="reason" type="xs:string"/>
	<xs:element name="reason_objection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="reason"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="remark" type="xs:string"/>
	<xs:element name="route">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lat"/>
				<xs:element ref="long"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="route_id_number" type="xs:string"/>
	<xs:element name="routes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="route"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ship_name" type="xs:string"/>
	<xs:element name="voyage_number" type="xs:string"/>
</xs:schema>

=== heavenlxj/emgui/src/schema/object.xml
<?xml version="1.0" encoding="UTF-8"?>
<objection_report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="object.xsd">
	<Property>
		<ship_name/>
		<call_sign/>
		<voyage_number/>
		<captain_name/>
		<date>2015-12-29</date>
		<route_id_number/>
		<routes>
			<route>
				<lat>40</lat>
				<long>30</long>
			</route>
		</routes>
		<reason_objection>
			<reason/>
		</reason_objection>
		<remark/>
	</Property>
</objection_report>
