=== heavenlxj/emgui/src/schema/request.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by 123 (456) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ship_name"/>
				<xs:element ref="call_sign"/>
				<xs:element ref="voyage_number"/>
				<xs:element ref="date"/>
				<xs:element ref="voyage_detail"/>
				<xs:element ref="via"/>
				<xs:element ref="use_dw_route"/>
				<xs:element ref="maximum_draft"/>
				<xs:element ref="load_condition"/>
				<xs:element ref="speed_setting"/>
				<xs:element ref="etd"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="call_sign" type="xs:string"/>
	<xs:element name="country" type="xs:string"/>
	<xs:element name="date" type="xs:date"/>
	<xs:element name="departure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="country"/>
				<xs:element ref="port"/>
				<xs:element ref="unlo_code"/>
				<xs:element ref="terminal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="destination">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="country"/>
				<xs:element ref="port"/>
				<xs:element ref="unlo_code"/>
				<xs:element ref="terminal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="etd" type="xs:string"/>
	<xs:element name="load_condition" type="xs:string"/>
	<xs:element name="maximum_draft" type="xs:string"/>
	<xs:element name="port">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="request_report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ship_name" type="xs:string"/>
	<xs:element name="speed_setting" type="xs:string"/>
	<xs:element name="terminal" type="xs:string"/>
	<xs:element name="unlo_code" type="xs:string"/>
	<xs:element name="use_dw_route" type="xs:boolean"/>
	<xs:element name="via">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="voyage_detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="departure"/>
				<xs:element ref="destination"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="voyage_number" type="xs:string"/>
</xs:schema>

=== heavenlxj/emgui/src/schema/request.xml
<?xml version="1.0" encoding="UTF-8"?>
<request_report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\admin\Desktop\request.xsd">
	<Property>
		<ship_name/>
		<call_sign/>
		<voyage_number/>
		<date>2015-12-10</date>
		<voyage_detail>
			<departure>
				<country/>
				<port/>
				<unlo_code/>
				<terminal/>
			</departure>
			<destination>
				<country/>
				<port/>
				<unlo_code/>
				<terminal/>
			</destination>
		</voyage_detail>
		<via>
			<port/>
		</via>
		<use_dw_route>true</use_dw_route>
		<maximum_draft/>
		<load_condition/>
		<speed_setting/>
		<etd/>
	</Property>
</request_report>
