=== heavenlxj/emgui/src/schema/share.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by 123 (456) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ship_name"/>
				<xs:element ref="call_sign"/>
				<xs:element ref="voyage_number"/>
				<xs:element ref="date"/>
				<xs:element ref="voyage_detail"/>
				<xs:element ref="via"/>
				<xs:element ref="use_dw_route"/>
				<xs:element ref="use_critial_point"/>
				<xs:element ref="critial_point"/>
				<xs:element ref="paper_chart"/>
				<xs:element ref="voyage_data"/>
				<xs:element ref="total_bunker_consumption"/>
				<xs:element ref="average_bunker_consumption_per_nm"/>
				<xs:element ref="remark"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="arrival">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="departure_date"/>
				<xs:element ref="departure_time"/>
				<xs:element ref="country"/>
				<xs:element ref="port"/>
				<xs:element ref="unlo_code"/>
				<xs:element ref="terminal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="average_bunker_consumption_per_nm">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ifo"/>
				<xs:element ref="mdo"/>
				<xs:element ref="lsfo"/>
				<xs:element ref="lsmdo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="average_me_rmp">
		<xs:complexType/>
	</xs:element>
	<xs:element name="average_slip">
		<xs:complexType/>
	</xs:element>
	<xs:element name="average_speed">
		<xs:complexType/>
	</xs:element>
	<xs:element name="call_sign">
		<xs:complexType/>
	</xs:element>
	<xs:element name="cargo_shipped">
		<xs:complexType/>
	</xs:element>
	<xs:element name="country">
		<xs:complexType/>
	</xs:element>
	<xs:element name="critial_point">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="point"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="date" type="xs:date"/>
	<xs:element name="departure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="departure_date"/>
				<xs:element ref="departure_time"/>
				<xs:element ref="country"/>
				<xs:element ref="port"/>
				<xs:element ref="unlo_code"/>
				<xs:element ref="terminal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="departure_date" type="xs:date"/>
	<xs:element name="departure_time" type="xs:time"/>
	<xs:element name="displacement">
		<xs:complexType/>
	</xs:element>
	<xs:element name="ifo">
		<xs:complexType/>
	</xs:element>
	<xs:element name="load_condition">
		<xs:complexType/>
	</xs:element>
	<xs:element name="lsfo">
		<xs:complexType/>
	</xs:element>
	<xs:element name="lsmdo">
		<xs:complexType/>
	</xs:element>
	<xs:element name="maximum_draft">
		<xs:complexType/>
	</xs:element>
	<xs:element name="mdo">
		<xs:complexType/>
	</xs:element>
	<xs:element name="me_revolution_distance">
		<xs:complexType/>
	</xs:element>
	<xs:element name="minimum_ukc">
		<xs:complexType/>
	</xs:element>
	<xs:element name="paper">
		<xs:complexType/>
	</xs:element>
	<xs:element name="paper_chart">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paper"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="point">
		<xs:complexType/>
	</xs:element>
	<xs:element name="port">
		<xs:complexType/>
	</xs:element>
	<xs:element name="remark">
		<xs:complexType/>
	</xs:element>
	<xs:element name="share_report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ship_name">
		<xs:complexType/>
	</xs:element>
	<xs:element name="terminal">
		<xs:complexType/>
	</xs:element>
	<xs:element name="total_bunker_consumption">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ifo"/>
				<xs:element ref="mdo"/>
				<xs:element ref="lsfo"/>
				<xs:element ref="lsmdo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="total_distance">
		<xs:complexType/>
	</xs:element>
	<xs:element name="total_streaming_time">
		<xs:complexType/>
	</xs:element>
	<xs:element name="unlo_code">
		<xs:complexType/>
	</xs:element>
	<xs:element name="use_critial_point" type="xs:boolean"/>
	<xs:element name="use_dw_route" type="xs:boolean"/>
	<xs:element name="via">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="voyage_data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="maximum_draft"/>
				<xs:element ref="minimum_ukc"/>
				<xs:element ref="load_condition"/>
				<xs:element ref="displacement"/>
				<xs:element ref="cargo_shipped"/>
				<xs:element ref="total_distance"/>
				<xs:element ref="total_streaming_time"/>
				<xs:element ref="average_speed"/>
				<xs:element ref="average_slip"/>
				<xs:element ref="me_revolution_distance"/>
				<xs:element ref="average_me_rmp"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="voyage_detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="departure"/>
				<xs:element ref="arrival"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="voyage_number">
		<xs:complexType/>
	</xs:element>
</xs:schema>

=== heavenlxj/emgui/src/schema/share.xml
<?xml version="1.0" encoding="UTF-8"?>
<share_report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\admin\Desktop\share.xsd">
	<Property>
		<ship_name/>
		<call_sign/>
		<voyage_number/>
		<date>2015-12-10</date>
		<voyage_detail>
			<departure>
				<departure_date>2015-12-10</departure_date>
				<departure_time>10:00:00</departure_time>
				<country/>
				<port/>
				<unlo_code/>
				<terminal/>
			</departure>
			<arrival>
				<departure_date>2015-12-10</departure_date>
				<departure_time>10:00:00</departure_time>
				<country/>
				<port/>
				<unlo_code/>
				<terminal/>
			</arrival>
		</voyage_detail>
		<via>
			<port/>
		</via>
		<use_dw_route>true</use_dw_route>
		<use_critial_point>true</use_critial_point>
		<critial_point>
			<point/>
		</critial_point>
		<paper_chart>
			<paper/>
		</paper_chart>
		<voyage_data>
			<maximum_draft/>
			<minimum_ukc/>
			<load_condition/>
			<displacement/>
			<cargo_shipped/>
			<total_distance/>
			<total_streaming_time/>
			<average_speed/>
			<average_slip/>
			<me_revolution_distance/>
			<average_me_rmp/>
		</voyage_data>
		<total_bunker_consumption>
			<ifo/>
			<mdo/>
			<lsfo/>
			<lsmdo/>
		</total_bunker_consumption>
		<average_bunker_consumption_per_nm>
			<ifo/>
			<mdo/>
			<lsfo/>
			<lsmdo/>
		</average_bunker_consumption_per_nm>
		<remark/>
	</Property>
</share_report>
